name: Automatic Application Build

# Builds project on every push and PR
on:  [push, pull_request]

env:
  path: fprime/Ref

jobs:
  build:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python
    steps:
      # checkout the repository
      - uses: actions/checkout@v2

      - name: prepare python pre-built environnement
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: test python is functionnal
        run: python -c "import sys; print(sys.version)"
      
      - name: Pepare dependencies python, cmake
        run: |
          python -m pip install --upgrade pip
          sudo apt install cmake -y
        
      # Init the virtual environnement (project script)
      - name: Prepare venv
        run: ./scripts/init-venv.sh

      # Build the project (project script)
      - name: Build the project
        run: ./scripts/build.sh ${path}

  local_unit_test:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - uses: actions/checkout@v2

      - name: prepare python pre-built environnement
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: test python is functionnal
        run: python -c "import sys; print(sys.version)"
      
      - name: Pepare dependencies python, cmake
        run: |
          python -m pip install --upgrade pip
          sudo apt install cmake -y
        
      # Init the virtual environnement (project script)
      - name: Prepare venv
        run: ./scripts/init-venv.sh

      # Build the unit tests and check them one by one in the app
      - name: Build the project
        run: ./scripts/unit-test.sh ${path}

  global_unit_test:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - uses: actions/checkout@v2

      - name: prepare python pre-built environnement
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: test python is functionnal
        run: python -c "import sys; print(sys.version)"
      
      - name: Pepare dependencies python, cmake
        run: |
          python -m pip install --upgrade pip
          sudo apt install cmake -y
        
      # Init the virtual environnement (project script)
      - name: Prepare venv
        run: ./scripts/init-venv.sh

      # Build all the unit tests
      - name: Build the project
        run: |
          cd ${path}
          fprime-util check --all