# This is a basic workflow to help you get started with Actions

name: Runner IP

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Echo IPV4 adresses
        run: ip -4 addr | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
      # Save the command results in a log file
      - name: Save the IP adresses in log file
        run: |
        ip -4 addr | grep -oP '(?<=inet\s)\d+(\.\d+){3}' > /ip/lastip.txt
        echo "$(date) IP served as self-hosted runner" >> /ip/log.txt
      # Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: IP addresses
          path: /ip/lastip.txt